name: Updates master branch from upstream repository

on:
  schedule:
  - cron: '00 20 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - run: |
        repo=$(echo ${{ github.repository }} | sed -e 's/hwinther/proxmox/')
        echo repo=$repo
        git remote add upstream https://github.com/$repo.git
        git fetch upstream

        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        
        git checkout master
        git rebase upstream/master
        
